# -*- coding: utf-8 -*-
"""eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veJQJupR3ftKRauV3sbsSefNAUmYhXaN

# **IMPORTING DEPENDENCIES**
"""

from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

df = pd.read_csv("/content/HealthcareProviders.csv")

"""# **BASIC EXPLORATION OF THE DATASET**"""

df.describe(include='all')

"""** ADDING A NEW COLUMN "MONEY DIFFERENCE" IN THE DATASET WHICH CALCULATES THE DIFFERENCE BETWEEN "AVERAGE SUBMITTED CHARGE AMOUNT" COLUMN AND THE "AVERAGE MEDICARE PAYMENT AMOUNT" COLUMN**"""

df["Average Submitted Charge Amount"] = df["Average Submitted Charge Amount"].replace(',', '', regex=True)

df["Average Medicare Payment Amount"] = df["Average Medicare Payment Amount"].replace(',', '', regex=True)

df["Money difference"] = df["Average Submitted Charge Amount"].astype(float) - df["Average Medicare Payment Amount"].astype(float)

"""# **Basic exploration of the dataset with the new column**"""

df.nunique()

(df.isnull().sum()/(len(df)))*100

df.describe(include='all').T

cat_cols=df.select_dtypes(include=['object']).columns
num_cols = df.select_dtypes(include=np.number).columns.tolist()
print("Categorical Variables:")
print(cat_cols)
print("Numerical Variables:")
print(num_cols)

"""# **GRAPHS TO SEE THE DISTRIBUTION OF THE DATA IN THE DIFFERENT NUMERICAL FIELDS**"""

for col in num_cols:
    print(col)
    print('Skew :', round(df[col].skew(), 2))
    plt.figure(figsize = (15, 4))
    plt.subplot(1, 2, 1)
    df[col].hist(grid=False)
    plt.ylabel('count')
    plt.subplot(1, 2, 2)
    sns.boxplot(x=df[col])
    plt.show()

"""# **USING THE SWEETVIZ LIBRARY TO GENERATE A EDA REPORT ON THE WHOLE DATASET WITH SPECIAL FOCUS ON THE MONEY DIFFERENCE COLUMN AND HOW IT IS CORRELATED TO THE OTHER COLUMNS IN THE DATASET**"""

pip install sweetviz
import sweetviz as sv
report = sv.analyze(df, target_feat='Money difference')
report.show_html('Report.html')

"""The above line of code will generate a html file called "Report.html". The sweetviz library generates a eda report of the dataset provided. In the report we find out that the money difference column has the most correlation with the provider type column. This means the some specific providers are charging higher amounts of money than is actually necessary for the procedures.

We also target the sepcific Money difference feature using the sweetviz to find out what is its distribution in relation to the other features.

# **GRAPHS TO SEE THE CORRELATION BETWEEN THE MONEY DIFFERENCE COLUMN AND THE OTHER COLUMNS IN THE DATA SET THAT SHOW CORRELATION WITH IT**
"""

fig, axarr = plt.subplots(2, 2, figsize=(40, 40))
df.groupby('Provider Type')['Money difference'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][0], fontsize=12)
axarr[0][0].set_title("Provider type Vs Money difference", fontsize=18)
plt.subplots_adjust(hspace=1.0)
plt.subplots_adjust(wspace=.5)
sns.despine()

"""In the above graph we see that Ambulatory Surgical Center providers has the highest difference in the money difference column. This indicates that the anomaly lies here and we should be able to identify fraudulant behaviour if we study the Ambulatory Surgical Center rows."""

fig, axarr = plt.subplots(2, 2, figsize=(40, 40))
df.groupby('Place of Service')['Money difference'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][0], fontsize=12)
axarr[0][0].set_title("Place of Service Vs Money difference", fontsize=18)
plt.subplots_adjust(hspace=1.0)
plt.subplots_adjust(wspace=.5)
sns.despine()

"""The above graph shows that procedures conducted in facilities have a higher money difference as compared to procedures conducted in offices.  """

fig, axarr = plt.subplots(2, 2, figsize=(40, 40))
df.groupby('Gender of the Provider')['Money difference'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][0], fontsize=12)
axarr[0][0].set_title("Gender of the Provider Vs Money difference", fontsize=18)
plt.subplots_adjust(hspace=1.0)
plt.subplots_adjust(wspace=.5)
sns.despine()

"""The above graph shows that procedures conducted by males have a higher money difference as compared to procedures conducted by females.  """

fig, axarr = plt.subplots(2, 2, figsize=(40, 40))
df.groupby('Entity Type of the Provider')['Money difference'].mean().sort_values(ascending=False).plot.bar(ax=axarr[0][0], fontsize=12)
axarr[0][0].set_title("Entity Type of the Provider Vs Money difference", fontsize=18)
plt.subplots_adjust(hspace=1.0)
plt.subplots_adjust(wspace=.5)
sns.despine()

"""The above graph shows that procedures conducted by organizations have a higher money difference as compared to procedures conducted by individuals.  """